[package]
name = "dda-send-checker"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
chrono = "0.4.42"
dotenv = "0.15.0"
ed25519 = "2.2.3"
russh = "0.54.6"
sqlx = { version = "0.8.6", features = ["postgres", "runtime-async-std", "macros", "mysql", "time"] }
tokio = { version = "1.48.0", features = ["full"] }
